## ==============================
## Nylas (Calendar Sync)
## ==============================
# Collez vos clés ici (Dashboard Nylas -> API Keys)
nylas.api.key=

nylas.client.id=




# Région Nylas (US par défaut). Si votre app est EU, changez en https://api.eu.nylas.com
nylas.base.url=https://api.us.nylas.com

# Callback OAuth (doit être identique à celui configuré dans le Dashboard Nylas)
nylas.redirect.uri=http://localhost:8888/callback

# Provider par défaut (google / microsoft)
nylas.provider=google
